#!/usr/bin/env python3
"""
Inject alt text from postcards-alts.json into the postcards wall project.
Creates postcards-alts-data.js and patches app.js and index.html.
"""

import json
import re
import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent
JSON_FILE = BASE_DIR / "postcards-alts.json"
DATA_JS = BASE_DIR / "postcards-alts-data.js"
APP_JS = BASE_DIR / "app.js"
INDEX_HTML = BASE_DIR / "index.html"


def create_data_js(data):
    """Generate postcards-alts-data.js with the alt text data."""
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    content = (
        "// Auto-generated by inject_alts.py — DO NOT EDIT MANUALLY\n"
        "// Run: python inject_alts.py to regenerate\n"
        f"var POSTCARD_ALTS = {json_str};\n"
    )
    DATA_JS.write_text(content, encoding="utf-8")
    print(f"Created {DATA_JS.name} ({len(data)} entries)")


def patch_app_js():
    """Patch app.js to use POSTCARD_ALTS for alt text."""
    text = APP_JS.read_text(encoding="utf-8")
    changed = False

    # Patch frontImg.alt
    old_front = "frontImg.alt = 'Postcard ' + (index + 1) + ' front';"
    new_front = (
        "frontImg.alt = (POSTCARD_ALTS['postcard-' + String(index + 1).padStart(3, '0') + '.webp'] "
        "|| 'Postcard ' + (index + 1)) + ' (front)';"
    )
    if old_front in text:
        text = text.replace(old_front, new_front)
        changed = True
        print("Patched frontImg.alt in app.js")
    elif new_front in text:
        print("frontImg.alt already patched")
    else:
        print("Warning: Could not find frontImg.alt pattern in app.js")

    # Patch backImg.alt
    old_back = "backImg.alt = 'Postcard ' + (index + 1);"
    new_back = (
        "backImg.alt = POSTCARD_ALTS['postcard-' + String(index + 1).padStart(3, '0') + '.webp'] "
        "|| 'Postcard ' + (index + 1);"
    )
    if old_back in text:
        text = text.replace(old_back, new_back)
        changed = True
        print("Patched backImg.alt in app.js")
    elif new_back in text:
        print("backImg.alt already patched")
    else:
        print("Warning: Could not find backImg.alt pattern in app.js")

    if changed:
        APP_JS.write_text(text, encoding="utf-8")


def patch_index_html():
    """Add script tag for postcards-alts-data.js before app.js in index.html."""
    text = INDEX_HTML.read_text(encoding="utf-8")

    if "postcards-alts-data.js" in text:
        print("index.html already has postcards-alts-data.js reference")
        return

    tag = '<script src="postcards-alts-data.js"></script>'
    # Insert before app.js script tag
    marker = '<script src="app.js"></script>'
    if marker in text:
        text = text.replace(marker, f"{tag}\n        {marker}")
        INDEX_HTML.write_text(text, encoding="utf-8")
        print("Added postcards-alts-data.js script tag to index.html")
    else:
        print("Warning: Could not find app.js script tag in index.html")


def main():
    if not JSON_FILE.exists():
        print(f"Error: {JSON_FILE.name} not found. Run ocr_pipeline.py first.")
        sys.exit(1)

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"Loaded {len(data)} entries from {JSON_FILE.name}\n")

    create_data_js(data)
    patch_app_js()
    patch_index_html()

    print("\nDone! Remember to test the page in a browser.")


if __name__ == "__main__":
    main()
